#ifndef PLANE_IMPLICIT_URDF_H
#define PLANE_IMPLICIT_URDF_H

//this file is autogenerated using stringify.bat (premake --stringify) in the build folder of this project
static const char* plane_implicit_urdf= \
"<?xml version=\"1.0\" ?>\n"
"<robot name=\"plane\">\n"
"  <link name=\"planeLink\">\n"
"	<contact>\n"
"      <lateral_friction value=\"0.9\"/>\n"
"    </contact>\n"
"    <inertial>\n"
"      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n"
"       <mass value=\".0\"/>\n"
"       <inertia ixx=\"0\" ixy=\"0\" ixz=\"0\" iyy=\"0\" iyz=\"0\" izz=\"0\"/>\n"
"    </inertial>\n"
"    <collision>\n"
"      <origin rpy=\"0 0 0\" xyz=\"0 0 0\"/>\n"
"      <!--<origin rpy=\"0 0 0\" xyz=\"0 0 -5\"/>-->\n"
"      <geometry>\n"
"	      <plane normal=\"0 0 1\"/>\n"
"	 			<!--<box size=\"100 100 10\"/>-->\n"
"      </geometry>\n"
"    </collision>\n"
"  </link>\n"
"</robot>\n"
;

#endif //PLANE_IMPLICIT_URDF_H